language: node_js

node_js: 'lts/*'

cache:
  directories:
    - ~/.npm

stages:
  - name: test
  - name: deploy
    if: tag =~ ^v

jobs:
  include:
    - name: 'node:lts'
      stage: test
      script:
        - npm run build
        - npm test
    - name: 'npm'
      stage: deploy
      script:
        - npm run build
      deploy:
        provider: npm
        skip-cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_APIKEY
        on:
          tags: true

notifications:
  email: false
